version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
  redis-insight:
    image: redis/redisinsight:latest
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - redis-net
    volumes:
      - type: volume
        source: redis-insight-data
        target: /app/volume-data

networks:
  redis-net:
    driver: bridge

volumes:
  redis-insight-data: 
    driver: local
