services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
  redis-insight:
    image: redis/redisinsight:latest
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - redis-net
    volumes:
      - type: volume
        source: redis-insight-data
        target: /app/volume-data
  app:
    image: ikit
    networks:
      - redis-net
    depends_on:
      - redis
    ports:
      - "3000:${PORT}"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT}
      FOOD_API_KEY: ${FOOD_API_KEY}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

  

networks:
  redis-net:
    driver: bridge

volumes:
  redis-insight-data: 
    driver: local
