version: "0"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis-net
  redis-insight:
    image: redis/redisinsight:latest
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
