name: Unit tests

on: push

jobs:
  auth-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v5

      - name: Set up nodejs enviroment
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install all dependencies
        run: npm ci

      - name: Start dev server in background
        run: npm run dev &

      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run tests
        run: npm run test:unit:auth
